"""
Research Assistant CLI

Command-line interface for the research assistant.
"""

import asyncio
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich.table import Table

from main import research, create_research_graph

# CLI app
app = typer.Typer(
    name="research-assistant",
    help="AI-powered research assistant using LangGraph",
    add_completion=False
)

# Rich console
console = Console()


@app.command()
def query(
    topic: str = typer.Argument(..., help="Research topic or query"),
    session: Optional[str] = typer.Option(None, "--session", "-s", help="Session ID for conversation continuity"),
    output: Optional[Path] = typer.Option(None, "--output", "-o", help="Save results to file"),
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Show detailed execution info")
):
    """
    Research a topic comprehensively.

    Example:
        research-assistant query "LangGraph capabilities"
        research-assistant query "Climate change impacts" --output results.md
    """

    async def run_research():
        if verbose:
            console.print(f"[dim]Topic: {topic}[/dim]")
            if session:
                console.print(f"[dim]Session: {session}[/dim]")

        # Show progress
        with Progress(
            SpinnerColumn(),
            TextColumn("[progress.description]{task.description}"),
            console=console
        ) as progress:
            task = progress.add_task("[cyan]Researching...", total=None)

            # Conduct research
            result = await research(topic, session_id=session)

        # Display results
        console.print("\n")
        console.print(Panel(
            Markdown(result.get("synthesis", "No synthesis generated")),
            title="[bold cyan]Research Results[/bold cyan]",
            border_style="cyan"
        ))

        # Display metadata
        if verbose:
            metadata_table = Table(title="Research Metadata")
            metadata_table.add_column("Metric", style="cyan")
            metadata_table.add_column("Value", style="green")

            metadata_table.add_row("Confidence", f"{result.get('confidence', 0):.2%}")
            metadata_table.add_row("Iterations", str(result.get('iteration_count', 0)))
            metadata_table.add_row("Web Results", str(len(result.get('web_results', []))))
            metadata_table.add_row("Paper Results", str(len(result.get('paper_results', []))))

            console.print("\n")
            console.print(metadata_table)

        # Save to file if requested
        if output:
            output_text = f"# Research Results: {topic}\n\n"
            output_text += result.get("synthesis", "")
            output_text += f"\n\n---\n\n"
            output_text += f"Confidence: {result.get('confidence', 0):.2%}\n"
            output_text += f"Generated by Research Assistant\n"

            output.write_text(output_text)
            console.print(f"\n[green]Results saved to: {output}[/green]")

    # Run async
    asyncio.run(run_research())


@app.command()
def interactive(
    session: Optional[str] = typer.Option(None, "--session", "-s", help="Session ID for conversation continuity")
):
    """
    Start an interactive research session.

    Example:
        research-assistant interactive
        research-assistant interactive --session my-research
    """
    from datetime import datetime

    # Generate session ID if not provided
    session_id = session or f"interactive-{datetime.now().strftime('%Y%m%d-%H%M%S')}"

    console.print(Panel(
        "[bold cyan]Interactive Research Assistant[/bold cyan]\n\n"
        f"Session ID: [yellow]{session_id}[/yellow]\n\n"
        "Enter research topics and get comprehensive answers.\n"
        "Commands: /exit, /help",
        border_style="cyan"
    ))

    async def research_loop():
        while True:
            # Get user input
            try:
                user_input = console.input("\n[bold green]Research topic:[/bold green] ")
            except (KeyboardInterrupt, EOFError):
                console.print("\n[yellow]Goodbye![/yellow]")
                break

            # Handle commands
            if user_input.strip().lower() == "/exit":
                console.print("[yellow]Goodbye![/yellow]")
                break

            elif user_input.strip().lower() == "/help":
                console.print("\n[bold cyan]Commands:[/bold cyan]")
                console.print("  /exit  - Exit the session")
                console.print("  /help  - Show this help message")
                continue

            if not user_input.strip():
                continue

            # Show progress
            with Progress(
                SpinnerColumn(),
                TextColumn("[progress.description]{task.description}"),
                console=console
            ) as progress:
                task = progress.add_task("[cyan]Researching...", total=None)

                # Conduct research
                result = await research(user_input, session_id=session_id)

            # Display results
            console.print("\n")
            console.print(Markdown(result.get("synthesis", "No synthesis generated")))
            console.print("\n" + "-" * 80)

    # Run research loop
    asyncio.run(research_loop())


@app.command()
def history(
    session: str = typer.Argument(..., help="Session ID to view"),
    format: str = typer.Option("pretty", "--format", "-f", help="Output format: pretty, json")
):
    """
    View research history for a session.

    Example:
        research-assistant history my-session
    """
    import json

    async def get_history():
        graph = create_research_graph()

        config = {
            "configurable": {
                "thread_id": session
            }
        }

        try:
            state = graph.get_state(config)

            if not state.values:
                console.print("[yellow]No history found for this session.[/yellow]")
                return

            # Extract relevant information
            query = state.values.get("query", "Unknown")
            synthesis = state.values.get("synthesis", "No synthesis")
            confidence = state.values.get("confidence", 0)

            if format == "json":
                history_data = {
                    "session_id": session,
                    "query": query,
                    "synthesis": synthesis,
                    "confidence": confidence
                }
                console.print_json(data=history_data)
            else:
                console.print(f"\n[bold cyan]Session: {session}[/bold cyan]")
                console.print(f"[cyan]Query:[/cyan] {query}")
                console.print(f"[cyan]Confidence:[/cyan] {confidence:.2%}\n")
                console.print(Panel(
                    Markdown(synthesis),
                    title="Research Synthesis",
                    border_style="cyan"
                ))

        except Exception as e:
            console.print(f"[red]Error: {e}[/red]")

    asyncio.run(get_history())


@app.command()
def stats():
    """
    Show research assistant statistics.

    Example:
        research-assistant stats
    """
    # TODO: Implement statistics from database
    console.print("[yellow]Statistics not yet implemented.[/yellow]")


if __name__ == "__main__":
    app()
